language: go

go:
  - 1.7
  - tip

matrix:
  allow_failures:
  - go: tip
  fast_finish: true

os:
  - linux
  - osx

env:
  global:
    - APM_TEST_PACKAGES="go-config"
    - NVM_DIR="$HOME/.nvm"
  matrix:
    - ATOM_CHANNEL=beta
    - ATOM_CHANNEL=stable

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - rm -rf "$NVM_DIR"
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | bash
  - source "$NVM_DIR/nvm.sh"
  - nvm install node
  - nvm use node
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u github.com/sqs/goreturns
  - go get -u golang.org/x/tools/cmd/cover

script:
  - 'curl -s https://raw.githubusercontent.com/atom/ci/943a16cd32926bdfcca703f16ec6a958a2db38a5/build-package.sh | sh'

sudo: false

git:
  depth: 10

addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot

branches:
  only:
    - master
